### ISSUE TITLE
Manual install instructions in readme are outdated

### ISSUE THREAD

**Issue by mtazzari** [adamkewley/jobson-1.0-throwaway#4]
I think these instructions in the README.md are outdated given the new structure with bin/ and share/ directories inside the tar gz.
```
Manual Install

    Download a binary tarball for your platform (e.g. *nix) from the releases page (e.g. jobson-nix-0.0.15.tar.gz)
    Unzip the tarball wherever you want jobson to be installed (e.g. /opt)
    (optional) Add the top-level jobson executable to the PATH (e.g. ln -s jobson /usr/local/bin/jobson)
```

**Comment by adamkewley** [comment]
The README in this repo should be merged into Jobson's. It doesn't contain that statement anymore, and the new README should just link users to the main documentation (to prevent needing to maintain duplicate guides).

I'll keep this open just in-case I forget/mis-merge though! Thank you for the feedback

**Comment by adamkewley** [comment]
Ah, wait, confusingly, the README isn't updated. I see what you mean now ;)

**Comment by adamkewley** [comment]
Now I understand: Github is defaulting to viewing an old branch, rather than master. I changed it in the GitHub settings and this should now be fixed:

https://github.com/adamkewley/jobson-1.0-throwaway

**Comment by mtazzari** [comment]
Ah ok, now I see.
It is fixed now :D
